language: go
go:
  - 1.5
  - tip

go_import_path: github.com/cloudfoundry/gorouter
matrix:
  allow_failures:
    - go: tip

install:
  - export PATH=$HOME/gopath/bin:$PATH

script:
  - ./scripts/test
